library config.globals;

import 'models/client.dart';

List<Client> client = [
  Client(
      prenom: 'Hasna',
      id: '6',
      nom: 'boufahja',
      idCoach: '1',
      credit: 45,
      gacaoch: 0,
      gacummul: 6,
      gaparrainage: 10,
      gaweek: 7,
      numTelephone: '58447154',
      email: 'hasnaboufahga@gmail.com',
      favArticles: [],
    ),
    Client(
      prenom: 'Foued',
      id: '7',
      nom: 'Hafnaoui',
      idCoach: '1',
      credit: 2,
      gacaoch: 14,
      gacummul: 0,
      gaparrainage: 10,
      gaweek: 7,
      numTelephone: '98547164',
      email: 'FouedHafnaoui@gmail.com',
      favArticles: [],
    ),
    Client(
      prenom: 'SeifEddine',
      id: '8',
      nom: 'Bakkouri',
      idCoach: '',
      credit: 82,
      gacaoch: 4,
      gacummul: 20,
      gaparrainage:  0,
      gaweek: 7,
      numTelephone: '98547164',
      email: 'FouedHafnaoui@gmail.com',
      favArticles: [],
    ),Client(
      prenom: 'Souhail',
      id: '9',
      nom: 'Jaballah',
      idCoach: '3',
      credit: 78,
      gacaoch: 8,
      gacummul: 24,
      gaparrainage: 0,
      gaweek: 7,
      numTelephone: '25787164',
      email: 'JaballahSouhail@gmail.com',
      favArticles: [],
    ),
];